# Generated by Django 3.1.2 on 2020-11-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('patient', 'patient'), ('doctor', 'doctor')], max_length=20)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.account')),
                ('department', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department_info',
            },
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.account')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('familyHistory', models.CharField(max_length=100)),
                ('surgicalHistory', models.CharField(max_length=100)),
                ('allergies', models.CharField(max_length=100)),
                ('bloodType', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'medical_info',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.account')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personal_info',
            },
        ),
    ]
