# Generated by Django 3.1.2 on 2020-11-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='account',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='account',
            new_name='id',
        ),
    ]
