# Generated by Django 3.1.2 on 2020-11-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201129_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='date',
            new_name='dateTime',
        ),
    ]
