# Generated by Django 3.1.2 on 2020-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201129_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='flag',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
