# Generated by Django 3.1.2 on 2020-11-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201122_1342'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
