# Generated by Django 3.1.2 on 2020-11-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201125_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('recordID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('symptoms', models.CharField(max_length=300)),
                ('treatments', models.CharField(max_length=300)),
                ('diagnosis', models.CharField(max_length=300)),
                ('attachments', models.FileField(upload_to='')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorID', to='api.account')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientID', to='api.account')),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
    ]
