# Generated by Django 3.1.2 on 2020-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medical_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_record',
            name='attachments',
        ),
        migrations.AddField(
            model_name='medical_record',
            name='attachmentNb',
            field=models.IntegerField(default=0),
        ),
    ]
